### ISSUE TITLE
Output file says - "it looks like we don't support this format"

### ISSUE THREAD

**Issue by jimgit** [itage-biz/MimeHtml2Html#5]
I have a number of mhtml files produced from Microsoft Reporting Services - exporting a report to mhtml

The file can be viewed in Internet Explorer

I would like to export the mhtml to png (or jpg).  Are there settings required for this?
Here's the destination file:

![image](https://user-images.githubusercontent.com/1921941/112727609-40c75580-8ef1-11eb-88ad-29fa279938e2.png)

Here's the code - 

        Dim conversionOptions = New MimeConversionOptions With {
            .CompressCss = True,
            .CompressHtml = True,
            .CompressImages = True,
            .JpegCompressorQuality = 100,
            .MaxPngColors = 256
        }
        Dim converter = New MimeConverter(conversionOptions)

        Using sourceStream As FileStream = File.OpenRead(fi.FullName)
            Using destinationStream As FileStream = File.Open(DestinationFilePath, FileMode.Create)
                converter.Convert(sourceStream, destinationStream)
            End Using
        End Using

**Comment by mjr27** [comment]
Unfortunatelly, no.

This this a file conversion utility that just takes mhtml files as input and outputs a single html file as output that could be opened in any browser.

My use case for it (actually, the reason why i created this tool it) is making html from headless chrome output . Probably, you should look here https://github.com/hardkoded/puppeteer-sharp -- this is the library for launching headless chrome, from which you can export page as an image:
